### ISSUE TITLE
KeyError: 'en' after starting bot, no notifications

### ISSUE THREAD

**Issue by PhDeez** [eugenio412/PogomBOT#18]
I am able to successfully launch the bot, and it starts as you can see, but after I "/addbyrarity 4" I see the error below and do not get any notifications.  I'm sure I just need to install something else, but I'm unsure what it is.  Furthermore, when I try to set language = en, it throws an error and says [] isn't available.

```
2016-08-19 11:44:58,352 - __main__ - INFO - Starting...
2016-08-19 11:44:58,353 - __main__ - INFO - Reading config.
2016-08-19 11:44:58,353 - __main__ - INFO - Reading pokemon names.
2016-08-19 11:44:58,353 - __main__ - INFO - Reading pokemon names.
2016-08-19 11:44:58,353 - __main__ - INFO - Reading pokemon names.
2016-08-19 11:44:58,354 - __main__ - INFO - Reading pokemon names.
2016-08-19 11:44:58,354 - __main__ - INFO - Token: <stuff>
2016-08-19 11:44:58,842 - __main__ - INFO - BotName: @<stuff>
2016-08-19 11:44:58,842 - __main__ - INFO - Started!
2016-08-19 11:45:29,663 - __main__ - INFO - [205043177] Starting.
2016-08-19 11:45:29,908 - __main__ - INFO - [205043177] Sending help text.
2016-08-19 11:45:40,261 - __main__ - INFO - [205043177] Adding job.
2016-08-19 11:45:40,502 - __main__ - INFO - [205043177] Add pokemon by rarity.
2016-08-19 11:45:40,502 - __main__ - INFO - [205043177] List.
2016-08-19 11:45:40,503 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 203, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/commandhandler.py", line 86, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pogobot.py", line 110, in addByRarity
    list(bot, update)
  File "pogobot.py", line 156, in list
    tmp += "%i %s\n" % (x, pokemon_name[lan][str(x)])
KeyError: 'en'

```

**Comment by PhDeez** [comment]
Started again so I can show what's on the terminal and in telegram...

```
2016-08-19 12:04:54,554 - __main__ - INFO - Started!
2016-08-19 12:04:57,628 - __main__ - INFO - [205043177] Starting.
2016-08-19 12:04:57,865 - __main__ - INFO - [205043177] Sending help text.
2016-08-19 12:05:04,087 - __main__ - INFO - [205043177] Setting lang.
2016-08-19 12:05:15,632 - __main__ - INFO - [205043177] Adding job.
2016-08-19 12:05:15,864 - __main__ - INFO - [205043177] Add pokemon by rarity.
2016-08-19 12:05:15,864 - __main__ - INFO - [205043177] List.
2016-08-19 12:05:15,865 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 203, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/commandhandler.py", line 86, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pogobot.py", line 110, in addByRarity
    list(bot, update)
  File "pogobot.py", line 156, in list
    tmp += "%i %s\n" % (x, pokemon_name[lan][str(x)])
KeyError: 'en'
^C^C2016-08-19 12:05:42,782 - telegram.ext.updater - WARNING - Exiting immediately!
~/pogom$ 
```

![screenshot_20160819-120457](https://cloud.githubusercontent.com/assets/21016588/17816100/6d0b454e-6605-11e6-87ef-0022810442cc.jpg)

**Comment by PhDeez** [comment]
FYI, I also tried starting the bot as a normal user and super (sudo) with the same results.  Platform is ubuntu.

```
ubuntu-server:~/pogom$ python3 --version
Python 3.4.3
ubuntu-server:~/pogom$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
ubuntu-server:~/pogom$ 
```

**Comment by Unknown66** [comment]
Did you copy the bot into the pogom map folder? It uses the same files for pokemon names.
And you need to run it from inside that folder too.

Would be helpfull if you could post `ls` from pogom folder. (And `ls static/locales` from inside pogom folder)

/lang [] means no languages could be loaded.

**Comment by PhDeez** [comment]
Here's an `ls`of my pogom directory and static/locales:

```
ubuntu-server:~/pogom$ ls
20160813.txt    20160818_2.txt     LICENSE          deploy-to-jelastic.png  pogobot.py    pogom.db-wal      templates
20160814.txt    20160818_3.txt     README.md        icon-32x32.png          pogom         requirements.txt
20160814_2.txt  Dockerfile         config-bot.json  manifest.jps            pogom.db      runserver.py
20160818.txt    ISSUE_TEMPLATE.md  config.json      nohup.out               pogom.db-shm  static
ubuntu-server:~/pogom$ cd static/locales/
ubuntu-server:~/pogom/static/locales$ 
ubuntu-server:~/pogom/static/locales$ ls
pokemon.de.json  pokemon.en.json  pokemon.fr.json  pokemon.zh_cn.json
ubuntu-server:~/pogom/static/locales$ 
```

Yes, the pogobot.py is in the same dir as the db it needs to read from.

Since @Unknown66 mentioned I needed to use a language in the static/locales folder I also tried de & fr with the same response in telegram as before with the weird [] response.  I also tried setting the config-bot.json to default language as "de" and it continued to show the weird response.

**Comment by PhDeez** [comment]
Also went ahead and deleted all PogomBOT files and then reinstalled via git clone, copied key back in to config-bot.json, copied files back to pogom still with the same result.  Is there an option for extended logging or is that output somewhere?

**Comment by Unknown66** [comment]
Did you start the pogoBOT from inside the pogom directory? Not from your homefolder.
With the new commit you get more error outputs, that could be helpful.

**Comment by PhDeez** [comment]
@Unknown66 Thanks for the help!  The new push does give extended logging which yields this info on execution.  I think we're starting to locate the problem

FWIW, I have pogom, PogomBOT and a few other Poke applications installed in my own user's home directory, ie: `/home/<user>/pogom/runserver.py`, not in /etc/, /opt/ or anywhere else.  And yes, I'm starting pogomBOT from the pogom directory, not the home directory or anything else...

```
ubuntu-server:~/pogom$ python3.4 pogobot.py
2016-08-19 21:48:09,135 - __main__:410 - INFO - Starting...
2016-08-19 21:48:09,135 - __main__:334 - INFO - Reading config.
2016-08-19 21:48:09,136 - __main__:347 - INFO - Reading pokemon names. [de]
Traceback (most recent call last):
  File "pogobot.py", line 353, in read_pokemon_names
    pokemon_name[loc] = json.loads(f.read())
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 420: ordil not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pogobot.py", line 453, in <module>
    main()
  File "pogobot.py", line 412, in main
    read_pokemon_names("de")
  File "pogobot.py", line 355, in read_pokemon_names
    logger.error('[%s] %s' % (chat_id, repr(e)))
NameError: name 'chat_id' is not defined
ubuntu-server:~/pogom$



```

Tracing down the error a bit, it looks like pokemon.de.json at position 420 is one of the Nidoran (looking like the girl one since it's poke#29), and the string is: `"Nidoran▒~Y~@"` which I guess the ascii parser doesn't like...  I don't recall changing this file ever, so it should be the original from pogom, and I don't recall seeing anything about normalizing the names in the install instructions for PogomBOT.

**Comment by Unknown66** [comment]
Could you do `file -i pokemon.de.json`?
It should be utf-8 if that's not the case I will fix it tomorrow. 
You already showed me another bug :+1:

**Comment by PhDeez** [comment]
It is!

```
ubuntu-server:~/pogom/static/locales$ file -i pokemon.de.json
pokemon.de.json: text/plain; charset=utf-8
ubuntu-server:~/pogom/static/locales$ file -i pokemon.en.json
pokemon.en.json: text/plain; charset=utf-8
ubuntu-server:~/pogom/static/locales$ file -i pokemon.fr.json
pokemon.fr.json: text/plain; charset=utf-8
ubuntu-server:~/pogom/static/locales$ file -i pokemon.zh_cn.json
pokemon.zh_cn.json: text/plain; charset=utf-8

```

Glad to help... :) sorry I don't know how to fix... :(

**Comment by Unknown66** [comment]
Should be fixed in #23. Please report if it's fixed.

**Comment by PhDeez** [comment]
It runs great now!  I do see an interesting line output from the terminal, it's:

`2016-08-20 09:18:47,431 - __main__:333 - ERROR - [205043177] RuntimeError('dictionary changed size during iteration',)`

This does not seem to impact functionality since I'm still getting updates... Excellent work, thank you!

**Comment by Unknown66** [comment]
I will check this today if I've got time to.
